// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMFNneHVCQ3ZtTwn_O831kjfXkeJmMotM',
    appId: '1:767727548490:web:58e4943eb35b691be70eb3',
    messagingSenderId: '767727548490',
    projectId: 'bedaya-final',
    authDomain: 'bedaya-final.firebaseapp.com',
    storageBucket: 'bedaya-final.appspot.com',
    measurementId: 'G-95J610RXJ3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiy4Cj5FrizJ4-O59IGZOvIy7wbtJ8TLU',
    appId: '1:767727548490:android:0c782cfd1682a7c1e70eb3',
    messagingSenderId: '767727548490',
    projectId: 'bedaya-final',
    storageBucket: 'bedaya-final.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLkN2KgYeAeRtPW9DcbqG_6tlZi_WE_jM',
    appId: '1:767727548490:ios:7a3e0df619967853e70eb3',
    messagingSenderId: '767727548490',
    projectId: 'bedaya-final',
    storageBucket: 'bedaya-final.appspot.com',
    iosClientId: '767727548490-fuc1pqa0nf9mlupmo51rilv4gikdtjnj.apps.googleusercontent.com',
    iosBundleId: 'com.onatcipli.networkUpp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLkN2KgYeAeRtPW9DcbqG_6tlZi_WE_jM',
    appId: '1:767727548490:ios:7a3e0df619967853e70eb3',
    messagingSenderId: '767727548490',
    projectId: 'bedaya-final',
    storageBucket: 'bedaya-final.appspot.com',
    iosClientId: '767727548490-fuc1pqa0nf9mlupmo51rilv4gikdtjnj.apps.googleusercontent.com',
    iosBundleId: 'com.onatcipli.networkUpp',
  );
}
